apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: resdock-admin
    qcloud-app: resdock-admin
  name: resdock-admin
  namespace: kdl
spec:
  clusterIP: 192.168.253.165
  clusterIPs:
  - 192.168.253.165
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 16001-16001-tcp-2wo042npxzm
    port: 16001
    protocol: TCP
    targetPort: 16001
  selector:
    k8s-app: resdock-admin
    qcloud-app: resdock-admin
  sessionAffinity: None
  type: ClusterIP