apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: ""
  name: fl-manager
  namespace: kdl
  labels:
    k8s-app: fl-manager
    qcloud-app: fl-manager
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: fl-manager
      qcloud-app: fl-manager
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: fl-manager
        qcloud-app: fl-manager
    spec:
      affinity: {}
      containers:
      - env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: TZ
          value: Asia/Shanghai
        image: ccr.ccs.tencentyun.com/kdlproxy/manager:manager-v0.0.1
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 5
        name: fl-manager
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - sleep 3
          failureThreshold: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 4
        resources:
          limits:
            cpu: 1500m
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 256Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/config/
          name: feiliu-manager
          readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: kdlproxy
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: feiliu-manager
        name: feiliu-manager
