apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: ""
  name: resdock-cab-3
  namespace: kdl
  labels:
    k8s-app: resdock-cab
    qcloud-app: resdock-cab-3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      pod-app: resdock-cab
      k8s-app: resdock-cab-3
      qcloud-app: resdock-cab-3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        pod-app: resdock-cab
        k8s-app: resdock-cab-3
        qcloud-app: resdock-cab-3
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: k8s
                operator: In
                values:
                - node3
            weight: 1
      containers:
      - env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: TZ
          value: Asia/Shanghai
        image: ccr.ccs.tencentyun.com/kdlproxy/cab:cab-v0.11
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 5
        name: resdock-cab
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - sleep 3
          failureThreshold: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 4
        resources:
          limits:
            cpu: 1500m
            memory: 1Gi
          requests:
            cpu: 300m
            memory: 256Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
        - mountPath: /app/config/
          name: resdock-cab
          readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: kdlproxy
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: timezone
      - configMap:
          defaultMode: 420
          name: resdock-cab-3
        name: resdock-cab