apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: ""
  name: kdl-auth-hub
  namespace: kdl
  labels:
    app: auth
    k8s-app: kdl-auth-hub
    qcloud-app: kdl-auth-hub
spec:
  progressDeadlineSeconds: 600
  replicas: 6
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: auth
      k8s-app: kdl-auth-hub
      qcloud-app: kdl-auth-hub
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: auth
        k8s-app: kdl-auth-hub
        qcloud-app: kdl-auth-hub
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: k8s
                operator: In
                values:
                - node1
                - node2
                - node3
            weight: 1
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: auth
                    k8s-app: kdl-auth-hub
                    qcloud-app: kdl-auth-hub
              weight: 1
      containers:
      - image: ccr.ccs.tencentyun.com/kdlproxy/kdl-auth-hub:v2.1.25
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 5
        name: kdl-auth-hub
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - sleep 3
          failureThreshold: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 4
        resources:
          limits:
            cpu: 1500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 256Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/log
          name: data2
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: kdlproxy
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /data2/log/auth
          type: DirectoryOrCreate
        name: data2