apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
    k8s-app: kdl-auth-hub
    qcloud-app: kdl-auth-hub
spec:
  clusterIP: 192.168.255.170
  clusterIPs:
  - 192.168.255.170
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 9090-9090-tcp-2ylkwjitlf2
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: 6061-6061-tcp-2wmvbfddfxg
    port: 6061
    protocol: TCP
    targetPort: 6061
  - name: tcp
    port: 10001
    protocol: TCP
    targetPort: 10001
  selector:
    app: auth
    k8s-app: kdl-auth-hub
    qcloud-app: kdl-auth-hub
  sessionAffinity: None
  type: ClusterIP
