apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: resdock-cab-svc
    qcloud-app: resdock-cab-svc
  name: resdock-cab
  namespace: kdl
spec:
  clusterIP: 192.168.253.160
  clusterIPs:
  - 192.168.253.160
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 16001-16001-tcp-2wo042npxzm
    port: 16001
    protocol: TCP
    targetPort: 16001
  selector:
    pod-app: resdock-cab
  sessionAffinity: None
  type: ClusterIP