- name: update kps
  shell: svn up --username 'kps' --password '$SbHA*5pw#' /root/kps 
- name: download file
  get_url:
    url: ""
    dest: /opt/
    validate_certs: no
- name: Unarchive tar file
  unarchive:
    src: /opt/categraf-v0.2.35-linux-amd64.tar.gz
    dest: /opt/
    remote_src: yes
- name: link file
  file:
    src: /opt/categraf-v0.2.35-linux-amd64
    dest: "{{ agent_path }}"
    state: link
- name: copy file
  copy:
    src: "{{ agent_path }}/conf/categraf.service"
    dest: /etc/systemd/system/
    remote_src: yes
  notify: reload daemon

- name: change config
  shell: |
    sed -ri '11c\hostname = ""' "{{ agent_path }}/conf/config.toml"
    sed -ri '20c\interval = 30' "{{ agent_path }}/conf/config.toml"
    sed -ri '52c\url = "http://:17000/prometheus/v1/write"' "{{ agent_path }}/conf/config.toml"
    sed -ri '75c\enable = true' "{{ agent_path }}/conf/config.toml"
    sed -ri '79c\servers = [":20090"]' "{{ agent_path }}/conf/config.toml"
    sed -ri '84c\enable = true' "{{ agent_path }}/conf/config.toml"
    sed -ri '87c\url = "http://:17000/v1/n9e/heartbeat"'  "{{ agent_path }}/conf/config.toml"
  notify: restart monitor
