apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: eip-eps
    qcloud-app: eip-eps
  name: eip-eps
  namespace: kdl
spec:
  clusterIP: 192.168.253.175
  clusterIPs:
  - 192.168.253.175
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 16001-16001-tcp-2wo042npxzm
    port: 7070
    protocol: TCP
    targetPort: 7070
  selector:
    k8s-app: eip-eps
    qcloud-app: eip-eps
  sessionAffinity: None
  type: ClusterIP