apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 7
  name: eip-etask
  namespace: kdl
  labels:
    k8s-app: eip-etask
    qcloud-app: eip-etask
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: eip-etask
      qcloud-app: eip-etask
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: eip-etask
        qcloud-app: eip-etask
    spec:
      affinity: {}
      containers:
      - env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: TZ
          value: Asia/Shanghai
        image: ccr.ccs.tencentyun.com/kdlproxy/etask:1.0.0
        imagePullPolicy: Always
        name: eip-etask
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - mountPath: /app/conf/
          name: eip-etask
          readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: kdlproxy
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: timezone
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
      - configMap:
          defaultMode: 420
          name: eip-etask
        name: eip-etask