apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: ""
  generation: 9
  labels:
    k8s-app: cron-cn-node
    qcloud-app: cron-cn-node
  name: fl-cron-cn-node
  namespace: kdl
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: cron-cn-node
      qcloud-app: cron-cn-node
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: cron-cn-node
        qcloud-app: cron-cn-node
    spec:
      affinity: {}
      containers:
      - env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: TZ
          value: Asia/Shanghai
        image: ccr.ccs.tencentyun.com/kdlproxy/cron_cn_node:cron_cn_node-v0.0.1
        imagePullPolicy: Always
        name: fl-cron-cn-node
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - mountPath: /app/config
          name: cron-cn-node-config
          readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: kdlproxy
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: timezone
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
      - configMap:
          defaultMode: 420
          name: cron-cn-node
        name: cron-cn-node-config